---
- name: check for short-circuit
  raw: "test -d /etc/zookeeper"
  register: installed
  ignore_errors: True
  changed_when: False

- name: set should_run fact
  set_fact: 
    should_run: "{{installed|failed or not zookeeper_should_shortcircuit}}"
  
- include: compat.yml

- include: include_vars.yml

# Install EPEL
- include: epel.yml
  when: ansible_distribution == 'CentOS'

- include: Debian.yml
  when: ansible_os_family == 'Debian'

- include: RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: install_package_names.yml

- name: Install zoo.cfg
  sudo: True
  template: >
    src=zoo.cfg.j2
    dest={{zookeeper_cfg_file}}
    owner=root
  notify: restart zookeeper

- name: Install myid
  sudo: True
  template: >
    src=myid.j2
    dest={{zookeeper_myid_file}}
    owner=root
  notify: restart zookeeper

- name: Ensure zookeeper enabled
  sudo: True
  service: name=zookeeper enabled={{zookeeper_enabled}} state={{zookeeper_state}}
  # Workaround https://github.com/ansible/ansible/issues/9074
  changed_when: False
  # Does not work in CentOS7 or Fedora in CircleCI
  when: not (is_integration_test is defined and
        is_integration_test and (ansible_os_family == "RedHat" or
           ansible_distribution == "CentOS"))
